(() => {
  const buttons = [document.querySelector('#adminButton'), document.querySelector('#homeAdmin')].filter(Boolean);
  const panel = document.querySelector('#adminPanel');
  const content = document.querySelector('#adminContent');
  const message = document.querySelector('#adminMessage');
  if (!panel || !content) return;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api = async (action, payload = {}) => { const response = await fetch('/api/admin/config', {method: action ? 'POST' : 'GET', headers: {'Content-Type':'application/json'}, body: action ? JSON.stringify({action, ...payload}) : undefined}); if (!response.ok) throw new Error(await response.text()); return response.json(); };
  const show = text => { message.textContent = text || ''; };
  let data = {whitelist: [], users: [], providers: []};
  const pages = {
    whitelist: () => `<div class="admin-page-head"><h1>IP 白名单</h1><p>只有白名单地址可以访问系统配置和 root 会话。</p></div><form class="admin-form" data-action="whitelist_add"><input name="cidr" required placeholder="IP 或 CIDR，例如 1.2.3.4/32"><input name="description" placeholder="说明"><button>添加白名单</button></form><div class="admin-table"><div class="admin-row admin-row-head"><span>地址</span><span>说明</span><span>操作</span></div>${data.whitelist.map(x => `<div class="admin-row"><code>${esc(x.cidr)}</code><span>${esc(x.description)}</span><span><button data-delete="whitelist_delete" data-id="${x.id}">删除</button></span></div>`).join('')}</div>`,
    users: () => `<div class="admin-page-head"><h1>用户管理</h1><p>创建和管理普通用户；root 用户由白名单访问自动使用。</p></div><form class="admin-form" data-action="user_add"><input name="username" required minlength="3" placeholder="用户名"><input name="email" type="email" placeholder="邮箱（可选）"><input name="password" required minlength="8" type="password" placeholder="初始密码"><button>创建用户</button></form><div class="admin-table"><div class="admin-row admin-row-head"><span>用户</span><span>状态</span><span>操作</span></div>${data.users.map(x => `<div class="admin-row"><span><b>${esc(x.username)}</b><small>${esc(x.email)}</small></span><span>${esc(x.status)}</span><span><button data-status="${x.id}" data-value="${x.status === 'active' ? 'disabled' : 'active'}">${x.status === 'active' ? '禁用' : '启用'}</button></span></div>`).join('')}</div>`,
    providers: () => `<div class="admin-page-head"><h1>Agent / Provider</h1><p>API Key 只保存加密密文，页面不会回显完整 Key。</p></div><form class="admin-form provider-form" data-action="provider_add"><input name="name" required placeholder="配置名称"><input name="base_url" required placeholder="https://api.example.com/v1/chat/completions"><input name="api_key" required type="password" placeholder="API Key"><input name="default_model" required value="gpt-5.5" placeholder="默认模型"><button>保存配置</button></form><div class="admin-table"><div class="admin-row admin-row-head"><span>配置</span><span>模型 / Key</span><span>操作</span></div>${data.providers.map(x => `<div class="admin-row"><span><b>${esc(x.name)}</b><small>${esc(x.base_url)}</small></span><span>${esc(x.default_model)}<small>${esc(x.api_key_hint || '已加密')}</small></span><span><button data-provider-status="${x.id}" data-value="${x.enabled ? 'false' : 'true'}">${x.enabled ? '禁用' : '启用'}</button><button data-delete="provider_delete" data-id="${x.id}">删除</button></span></div>`).join('')}</div>`
  };
  let current = 'whitelist';
  const render = () => { content.innerHTML = pages[current](); document.querySelectorAll('.admin-tab').forEach(x => x.classList.toggle('active', x.dataset.section === current)); };
  const refresh = async () => { show('加载中…'); try { data = await api(); render(); show(''); } catch (error) { show(error.message || '无权访问配置页'); } };
  const open = () => { panel.classList.remove('hidden'); render(); refresh(); };
  buttons.forEach(button => button.onclick = open);
  document.querySelector('#closeAdmin').onclick = () => panel.classList.add('hidden');
  panel.addEventListener('click', async event => { const target = event.target; if (target.classList.contains('admin-tab')) { current = target.dataset.section; render(); return; } try { if (target.dataset.delete) { await api(target.dataset.delete, {id: Number(target.dataset.id)}); await refresh(); } if (target.dataset.status) { await api('user_status', {id: Number(target.dataset.status), status: target.dataset.value}); await refresh(); } if (target.dataset.providerStatus) { await api('provider_status', {id: Number(target.dataset.providerStatus), enabled: target.dataset.value === 'true'}); await refresh(); } } catch (error) { show(error.message); } });
  panel.addEventListener('submit', async event => { event.preventDefault(); const form = event.target; try { await api(form.dataset.action, Object.fromEntries(new FormData(form))); await refresh(); } catch (error) { show(error.message); } });
  fetch('/api/admin/config').then(response => { if (response.ok) buttons.forEach(button => button.classList.remove('hidden')); }).catch(() => {});
})();
