const state={conversations:[],activeId:null,messages:[],busy:false,models:[],defaultModel:'',attachments:[]};
const $=s=>document.querySelector(s);const authHeaders=()=>{const key=localStorage.getItem('waf_api_key');return key?{'X-API-Key':key}:{}};
function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function contentText(content){if(Array.isArray(content))return content.filter(x=>x&&x.type==='text').map(x=>x.text||'').join('\n');if(typeof content==='string'){try{const parsed=JSON.parse(content);if(Array.isArray(parsed))return contentText(parsed)}catch(e){}return content}return ''}
function normalizeMessage(message){if(typeof message.content==='string'){try{const parsed=JSON.parse(message.content);if(Array.isArray(parsed))return {...message,content:parsed}}catch(e){}}return message}
function renderMessageContent(content){if(!Array.isArray(content))return escapeHTML(contentText(content));return content.map(part=>{if(part.type==='image_url'&&part.image_url?.url?.startsWith('data:image/'))return `<img class="message-image" src="${escapeHTML(part.image_url.url)}" alt="上传的图片">`;if(part.type==='text')return escapeHTML(part.text||'');return ''}).join('')}
function syncModel(model){const select=$('#modelSelect');if(!select||!model)return;if([...select.options].some(x=>x.value===model))select.value=model}
function scrollMessagesToBottom(){requestAnimationFrame(()=>{const box=$('#messages');if(box)box.scrollTop=box.scrollHeight})}
function renderConversations(){const el=$('#conversationList');el.innerHTML=state.conversations.map(c=>`<div class="conversation ${c.id===state.activeId?'active':''}" data-id="${c.id}"><span>${escapeHTML(c.title||'新对话')}</span></div>`).join('');el.querySelectorAll('.conversation').forEach(x=>x.onclick=async()=>{state.activeId=x.dataset.id;const item=state.conversations.find(c=>c.id===state.activeId);state.messages=[];syncModel(item&&item.model);renderConversations();renderMessages();try{const r=await fetch('/api/conversations/messages?id='+encodeURIComponent(state.activeId));if(!r.ok)throw new Error(await r.text());const d=await r.json();state.messages=d.messages||[];if(item)item.messages=state.messages;renderMessages()}catch(e){console.error('load conversation failed',e)}})}
function renderMessages(){const box=$('#messages');box.innerHTML=state.messages.map(m=>`<div class="message ${m.role}"><div class="bubble">${renderMessageContent(m.content)}</div></div>`).join('');scrollMessagesToBottom();$('#welcome').classList.toggle('hidden',state.messages.length>0)}
function newChat(){state.activeId=crypto.randomUUID();state.messages=[];state.conversations.unshift({id:state.activeId,title:'新对话',model:$('#modelSelect').value||state.defaultModel,messages:state.messages});renderConversations();renderMessages();$('#prompt').focus()}
function addMessage(role,content){const m={role,content};state.messages.push(m);const c=state.conversations.find(c=>c.id===state.activeId);if(c){c.messages=state.messages;if(role==='user'&&c.title==='新对话')c.title=contentText(content).slice(0,24)||'附件对话'}renderConversations();renderMessages();return m}
async function loadModels(){try{const r=await fetch('/api/models');if(!r.ok)throw new Error(await r.text());const d=await r.json();state.models=d.models||[];state.defaultModel=d.default||state.models[0]?.id||'';const select=$('#modelSelect');select.innerHTML=state.models.map(m=>`<option value="${escapeHTML(m.id)}">${escapeHTML(m.name||m.id)}</option>`).join('');syncModel(state.conversations.find(c=>c.id===state.activeId)?.model||state.defaultModel);select.disabled=state.models.length===0;$('#statusDot').className='ok';$('#statusText').textContent=state.models.length?'服务已连接':'暂无可用模型'}catch(e){$('#modelSelect').innerHTML='<option value="">请先登录</option>';$('#modelSelect').disabled=true;$('#statusDot').className='bad';$('#statusText').textContent='模型服务未连接'}}
async function loadConversations(){try{const r=await fetch('/api/conversations');if(!r.ok)return;const d=await r.json();state.conversations=(d.conversations||[]).map(c=>({...c,messages:[]}));if(state.conversations.length){state.activeId=state.conversations[0].id;syncModel(state.conversations[0].model);const m=await fetch('/api/conversations/messages?id='+encodeURIComponent(state.activeId));if(m.ok){const body=await m.json();state.messages=(body.messages||[]).map(normalizeMessage);state.conversations[0].messages=state.messages}}else{newChat();return}renderConversations();renderMessages();scrollMessagesToBottom()}catch(e){console.debug('history unavailable',e)}}
function renderAttachments(){const el=$('#attachmentList');el.innerHTML=state.attachments.map((file,index)=>`<div class="attachment-item"><span>${file.kind==='image'?'🖼️':'📄'} ${escapeHTML(file.name)}</span><button type="button" data-remove-attachment="${index}" aria-label="移除附件">×</button></div>`).join('');el.classList.toggle('hidden',state.attachments.length===0)}
function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error(`读取文件失败：${file.name}`));if(file.type.startsWith('image/'))reader.readAsDataURL(file);else reader.readAsText(file)})}
async function addFiles(files){for(const file of files){if(state.attachments.length>=3){alert('最多同时上传 3 个文件');break}if(file.size>5*1024*1024){alert(`${file.name} 超过 5MB 限制`);continue}const isImage=file.type.startsWith('image/');const isText=!isImage&&(/\.(txt|md|csv|json|log|xml|yaml|yml)$/i.test(file.name)||file.type.startsWith('text/'));if(!isImage&&!isText){alert(`${file.name} 暂不支持，请上传图片或文本文件`);continue}try{const data=await readFile(file);state.attachments.push({name:file.name,kind:isImage?'image':'text',data});renderAttachments()}catch(e){alert(e.message)}}}
function buildUserContent(text){const parts=[];if(text)parts.push({type:'text',text});for(const file of state.attachments){if(file.kind==='image')parts.push({type:'image_url',image_url:{url:file.data}});else parts.push({type:'text',text:`\n\n[文件：${file.name}]\n${file.data}`})}return parts.length===1&&parts[0].type==='text'?parts[0].text:parts}
async function sendMessage(text){if(state.busy)return;if(!$('#modelSelect').value){alert('请先选择一个模型');return}if(!text&&state.attachments.length===0)return;if(!state.activeId)newChat();const model=$('#modelSelect').value;const conversation=state.conversations.find(c=>c.id===state.activeId);if(conversation)conversation.model=model;const userContent=buildUserContent(text);state.attachments=[];renderAttachments();addMessage('user',userContent);const assistant=addMessage('assistant','');const assistantBubble=$('#messages .assistant:last-child .bubble');let queue='',streamDone=false,finishTyping;const typingDone=new Promise(resolve=>finishTyping=resolve);const paint=loading=>{if(!assistantBubble)return;assistantBubble.textContent=assistant.content;if(loading){const dots=document.createElement('span');dots.className='typing-dots';dots.innerHTML='<i></i><i></i><i></i>';assistantBubble.appendChild(dots)}scrollMessagesToBottom()};const typingTimer=setInterval(()=>{if(queue){assistant.content+=queue[0];queue=queue.slice(1);paint(false)}else if(streamDone){clearInterval(typingTimer);paint(false);finishTyping()}else{paint(true)}},24);const push=chunk=>{queue+=chunk};state.busy=true;$('#sendButton').disabled=true;$('#modelSelect').disabled=true;try{const r=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({conversation_id:state.activeId,model,messages:state.messages.filter(x=>x!==assistant)})});if(!r.ok||!r.body){const detail=await r.text();if(r.status===413)throw new Error('图片或文件过大，请压缩后重试');throw new Error(detail||`请求失败（HTTP ${r.status}）`)}const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const parts=buffer.split('\n\n');buffer=parts.pop();for(const part of parts){const line=part.split('\n').find(x=>x.startsWith('data:'));if(!line)continue;const payload=line.slice(5).trim();if(payload==='[DONE]')continue;try{const evt=JSON.parse(payload);if(evt.error)throw new Error(evt.error);push(evt.delta||evt.content||'')}catch(e){if(e.message)throw e}}}}catch(e){push(`\n\n请求失败：${e.message}`)}finally{streamDone=true;await typingDone;state.busy=false;$('#sendButton').disabled=state.models.length===0;$('#modelSelect').disabled=state.models.length===0}}
function showChat(){ $('#homePage').classList.add('hidden'); $('#chatShell').classList.remove('hidden'); if(!state.activeId)newChat(); scrollMessagesToBottom(); }
$('#enterChat').onclick=showChat;$('#backHome').onclick=()=>{ $('#chatShell').classList.add('hidden'); $('#homePage').classList.remove('hidden'); };$('#newChat').onclick=newChat;$('#attachButton').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{addFiles([...e.target.files]);e.target.value=''};$('#attachmentList').onclick=e=>{const index=e.target.dataset.removeAttachment;if(index!==undefined){state.attachments.splice(Number(index),1);renderAttachments()}};$('#prompt').onpaste=e=>{const files=[...e.clipboardData.files];if(files.length){e.preventDefault();addFiles(files)}};$('#modelSelect').onchange=()=>{const c=state.conversations.find(c=>c.id===state.activeId);if(c)c.model=$('#modelSelect').value};$('#composer').onsubmit=e=>{e.preventDefault();const input=$('#prompt');const text=input.value.trim();if(text||state.attachments.length){input.value='';input.style.height='auto';sendMessage(text)}};$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}};newChat();window.addEventListener('auth:ready',()=>{loadModels();loadConversations()});
